// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import PhotoDropzoneController from "./photo_dropzone_controller"
application.register("photo-dropzone", PhotoDropzoneController)

import ThumbPlaceholderController from "./thumb_placeholder_controller"
application.register("thumb-placeholder", ThumbPlaceholderController)
